{% set name = "meggie" %}
{% set version = "1.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9ac69f9c3044e08b825f2f22ba73e782cf670e4a85fa5a92daa0e8ff377a4186

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - meggie = meggie.run:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - mne ==1.3.1
    - numpy ==1.23.5
    - matplotlib-base
    - scikit-learn
    - python-json-logger
    - pyqt
    - h5io

test:
  imports:
    - meggie

app:
  entry: meggie
  summary: User-friendly graphical user interface to do M/EEG analysis
  type: desk

about:
  home: https://github.com/cibr-jyu/meggie
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: User-friendly graphical user interface to do M/EEG analysis

extra:
  recipe-maintainers:
    - Teekuningas
