{% set name = "meggie" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1121cdf23e523d9a711348c3d4a6f39ad9349c10bd149b22c37eafcc02672fa6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - meggie = meggie.run:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - mne ==1.3.1
    - numpy ==1.23.5
    - matplotlib-base ==3.7.3
    - scikit-learn
    - python-json-logger
    - pyqt
    - h5io

test:
  imports:
    - meggie

app:
  entry: meggie
  summary: User-friendly graphical user interface to do M/EEG analysis
  type: desk

about:
  home: https://github.com/cibr-jyu/meggie
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: User-friendly graphical user interface to do M/EEG analysis

extra:
  recipe-maintainers:
    - Teekuningas
