{% set name = "meggie" %}
{% set version = "1.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 583f8a9a5fd8cc6a90d6b4765b638b3602d599d12ba2aeb3f08419c99659d633

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points: 
    - meggie = meggie.run:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - mne >=1.2.0
    - matplotlib-base
    - scikit-learn
    - python-json-logger
    - pyqt
    - numpy
    - h5io

test:
  imports:
    - meggie

app:
  entry: meggie
  summary: User-friendly graphical user interface to do M/EEG analysis
  type: desk

about:
  home: https://github.com/cibr-jyu/meggie
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: User-friendly graphical user interface to do M/EEG analysis

extra:
  recipe-maintainers:
    - Teekuningas
